export type Drama={id:string;title:string;year:string;genre:string;poster:any;synopsis:string;cast:string[]};
export type User={id:string;name:string;handle:string;avatar:string;bio:string;followers:number;following:number};
export type Post={id:string;userId:string;text:string;dramaIds:string[];time:string;likes:number;comments:number;saves:number;image?:any};
export const dramas:Drama[]=[
{id:'goblin',title:'Goblin',year:'2016',genre:'Fantasy • Romance',poster:require('../assets/dramas/goblin.png'),synopsis:'A lonely immortal guardian meets a spirited young woman who changes his fate.',cast:['Gong Yoo','Kim Go-eun','Lee Dong-wook']},
{id:'cloy',title:'Crash Landing on You',year:'2019',genre:'Romance • Comedy',poster:require('../assets/dramas/cloy.png'),synopsis:'An unexpected landing creates an unforgettable cross-border love story.',cast:['Hyun Bin','Son Ye-jin','Seo Ji-hye']},
{id:'glory',title:'The Glory',year:'2022',genre:'Revenge • Drama',poster:require('../assets/dramas/glory.png'),synopsis:'Years after brutal school abuse, a woman begins an elaborate plan for revenge.',cast:['Song Hye-kyo','Lee Do-hyun','Lim Ji-yeon']},
{id:'proposal',title:'Business Proposal',year:'2022',genre:'Romance • Comedy',poster:require('../assets/dramas/proposal.png'),synopsis:'A blind date turns into a workplace romance neither side expected.',cast:['Ahn Hyo-seop','Kim Se-jeong','Kim Min-kyu']}
];
export const users:User[]=[{id:'u1',name:'Mina Park',handle:'@minapark',avatar:'https://i.pravatar.cc/160?img=47',bio:'Collecting scenes that stay with me.',followers:1284,following:342},{id:'u2',name:'Jae',handle:'@jaeonair',avatar:'https://i.pravatar.cc/160?img=12',bio:'One more episode.',followers:842,following:201},{id:'u3',name:'Sora Kim',handle:'@sorakim',avatar:'https://i.pravatar.cc/160?img=32',bio:'Romance, revenge, repeat.',followers:4210,following:118}];
export let posts:Post[]=[{id:'p1',userId:'u1',text:'That final episode of Goblin still owns a tiny piece of my soul.',dramaIds:['goblin'],time:'12m',likes:284,comments:32,saves:41,image:require('../assets/ui/post-01.png')},{id:'p2',userId:'u2',text:'Need a new drama with this exact emotional damage. Recommendations?',dramaIds:['cloy'],time:'38m',likes:119,comments:18,saves:12},{id:'p3',userId:'u3',text:'The pacing in The Glory is ridiculously satisfying.',dramaIds:['glory'],time:'1h',likes:431,comments:57,saves:88,image:require('../assets/ui/post-02.png')}];
export function addPost(text:string,dramaIds:string[]){const p:Post={id:'local-'+Date.now(),userId:'u1',text,dramaIds,time:'now',likes:0,comments:0,saves:0};posts=[p,...posts];return p;}
