/* eslint-disable @typescript-eslint/no-require-imports */
import {
  Actor,
  Collection,
  Comment,
  Drama,
  Episode,
  Notification,
  Post,
  ReactionCounts,
  User,
  WatchlistItem,
  emptyReactions,
} from './model';

// ---------- helpers ----------
export const NOW = new Date('2026-09-19T19:30:00Z');
const iso = (d: Date) => d.toISOString();
const ago = (minutes: number) => iso(new Date(NOW.getTime() - minutes * 60_000));
const H = 60;
const D = 24 * H;
const at = (s: string) => new Date(s).toISOString();

const rx = (p: Partial<ReactionCounts>): ReactionCounts => ({ ...emptyReactions(), ...p });

/** Build episodes for a season: `start` ISO date (KST) with a weekly cadence pattern of weekday offsets. */
function episodes(
  dramaId: string,
  season: number,
  count: number,
  start: string,
  pattern: number[], // day offsets inside each week, e.g. [0,1] = Sat+Sun
  runtime = 70,
  titles: Record<number, string> = {},
): Episode[] {
  const out: Episode[] = [];
  const s = new Date(start);
  let n = 1;
  let week = 0;
  while (n <= count) {
    for (const off of pattern) {
      if (n > count) break;
      const d = new Date(s.getTime() + (week * 7 + off) * D * 60_000);
      out.push({ id: `${dramaId}-s${season}e${n}`, dramaId, season, number: n, airDate: iso(d), runtime, title: titles[n] });
      n++;
    }
    week++;
  }
  return out;
}

function drop(dramaId: string, season: number, count: number, date: string, runtime = 60): Episode[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `${dramaId}-s${season}e${i + 1}`,
    dramaId,
    season,
    number: i + 1,
    airDate: at(date),
    runtime,
  }));
}

type DramaSeed = Omit<Drama, 'episodes' | 'seasons' | 'episodeCount' | 'cast'> & {
  episodes: Episode[];
  seasons?: Drama['seasons'];
  cast: [string, string][];
};

function drama(s: DramaSeed): Drama {
  const seasons =
    s.seasons ??
    [...new Set(s.episodes.map((e) => e.season))].map((n) => ({
      number: n,
      episodeCount: s.episodes.filter((e) => e.season === n).length,
      year: new Date(s.episodes.find((e) => e.season === n)!.airDate!).getFullYear(),
    }));
  return {
    ...s,
    seasons,
    episodeCount: s.episodes.length,
    cast: s.cast.map(([actorId, role], i) => ({ actorId, role, order: i })),
  };
}

// ---------- dramas ----------
export const DRAMAS: Drama[] = [
  drama({
    id: 'a-love-other-than-yours',
    title: 'A Love Other Than Yours',
    originalTitle: '너와 다른 사랑',
    year: 2026,
    status: 'airing',
    network: 'KBS2',
    streamingOn: ['Prime Video'],
    genres: ['Romance', 'Melodrama'],
    tags: ['second chances', 'slow burn'],
    synopsis:
      'Two people who once chose duty over each other meet again in a coastal town, and discover that the love they left behind kept growing without them.',
    tone: '#3B2F4A',
    rating: 8.4,
    airsOn: 'Sat–Sun 21:20 KST',
    nextEpisodeAt: at('2026-09-19T12:20:00Z'),
    followerCount: 18_400,
    episodes: episodes('a-love-other-than-yours', 1, 14, '2026-09-12T12:20:00Z', [0, 1], 70, {
      1: 'The Tide Comes Back',
      2: 'What We Owed',
      3: 'Same Sky, Different Weather',
    }),
    cast: [
      ['seo-kang-joon', 'Lead'],
      ['ahn-eun-jin', 'Lead'],
    ],
  }),
  drama({
    id: 'the-scandal',
    title: 'The Scandal',
    originalTitle: '스캔들',
    year: 2026,
    status: 'completed',
    network: 'Netflix',
    streamingOn: ['Netflix'],
    genres: ['Historical', 'Romance', 'Melodrama'],
    tags: ['Joseon', 'seduction', 'remake'],
    synopsis:
      'A Joseon-era retelling of Untold Scandal: a notorious libertine and his cunning cousin turn a widow’s virtue into a wager — until the game stops being one.',
    tone: '#4A2A2E',
    rating: 8.1,
    followerCount: 41_200,
    episodes: drop('the-scandal', 1, 8, '2026-09-18T00:00:00Z', 62),
    cast: [
      ['son-ye-jin', 'Lady Jung'],
      ['ji-chang-wook', 'Jo-won'],
      ['nana', 'Lady Cho'],
    ],
  }),
  drama({
    id: 'made-in-korea',
    title: 'Made in Korea',
    originalTitle: '메이드 인 코리아',
    year: 2025,
    status: 'airing',
    network: 'Disney+',
    streamingOn: ['Disney+', 'Hulu'],
    genres: ['Crime', 'Thriller'],
    tags: ['1970s', 'political', 'cat and mouse'],
    synopsis:
      'Seoul, 1970s. A man who will do anything for money and power collides with a prosecutor who will do anything to stop him. Season 2 raises the stakes to the presidential palace.',
    tone: '#2F3A3F',
    rating: 8.0,
    airsOn: 'Wed 17:00 KST',
    nextEpisodeAt: at('2026-09-23T08:00:00Z'),
    followerCount: 22_900,
    episodes: [
      ...episodes('made-in-korea', 1, 6, '2025-12-24T08:00:00Z', [0], 65),
      ...episodes('made-in-korea', 2, 6, '2026-09-09T08:00:00Z', [0], 65, { 1: 'Blue House', 2: 'Ledger' }),
    ],
    cast: [
      ['hyun-bin', 'Baek Ki-tae'],
      ['jung-woo-sung', 'Jang Gun-young'],
    ],
  }),
  drama({
    id: 'the-ordinary-jackpot',
    title: 'The Ordinary Jackpot',
    originalTitle: '보통의 대박',
    year: 2026,
    status: 'airing',
    network: 'tvN',
    streamingOn: ['TVING'],
    genres: ['Comedy', 'Slice of life'],
    tags: ['lottery', 'family', 'feel-good'],
    synopsis:
      'A family that has never won anything wins everything at once — and finds out that ordinary was the jackpot all along.',
    tone: '#3F3A2A',
    rating: 7.6,
    airsOn: 'Thu 20:50 KST',
    nextEpisodeAt: at('2026-09-24T11:50:00Z'),
    followerCount: 6_300,
    episodes: episodes('the-ordinary-jackpot', 1, 10, '2026-09-10T11:50:00Z', [0], 68),
    cast: [],
  }),
  drama({
    id: 'dive-into-you',
    title: 'Dive into You',
    originalTitle: '너에게 빠지다',
    year: 2026,
    status: 'upcoming',
    network: 'Channel A',
    streamingOn: ['Viki', 'Disney+'],
    genres: ['Romance', 'Youth', 'Comedy'],
    tags: ['swimming', 'campus'],
    synopsis: 'A retired swimmer and the rookie who idolised her end up on the same struggling university team.',
    tone: '#243A4A',
    airsOn: 'Sat–Sun 22:00 KST',
    nextEpisodeAt: at('2026-09-26T13:00:00Z'),
    followerCount: 3_100,
    episodes: episodes('dive-into-you', 1, 12, '2026-09-26T13:00:00Z', [0, 1], 65),
    cast: [],
  }),
  drama({
    id: 'goblin',
    title: 'Goblin',
    originalTitle: '쓸쓸하고 찬란하神 도깨비',
    year: 2016,
    endYear: 2017,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Viki'],
    genres: ['Fantasy', 'Romance', 'Melodrama'],
    tags: ['immortal', 'bromance', 'fate'],
    synopsis:
      'A 939-year-old goblin needs a human bride to end his immortal life — then meets a girl who can see ghosts and refuses to be anyone’s ending.',
    posterLocal: require('../assets/dramas/goblin.png'),
    tone: '#2A2F3F',
    rating: 9.1,
    followerCount: 312_000,
    episodes: episodes('goblin', 1, 16, '2016-12-02T11:00:00Z', [0, 1], 80, {
      1: 'Immortal',
      13: 'The Sword',
      16: 'Rain',
    }),
    cast: [
      ['gong-yoo', 'Kim Shin'],
      ['kim-go-eun', 'Ji Eun-tak'],
      ['lee-dong-wook', 'Grim Reaper'],
      ['yoo-in-na', 'Sunny'],
      ['yook-sung-jae', 'Yoo Deok-hwa'],
    ],
    creators: ['Kim Eun-sook (writer)', 'Lee Eung-bok (director)'],
  }),
  drama({
    id: 'crash-landing-on-you',
    title: 'Crash Landing on You',
    originalTitle: '사랑의 불시착',
    year: 2019,
    endYear: 2020,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix'],
    genres: ['Romance', 'Comedy'],
    tags: ['border', 'found family'],
    synopsis: 'A paragliding accident lands a South Korean heiress in the North — and in the care of an officer who should have arrested her.',
    posterLocal: require('../assets/dramas/cloy.png'),
    tone: '#2F3A2A',
    rating: 9.0,
    followerCount: 287_000,
    episodes: episodes('crash-landing-on-you', 1, 16, '2019-12-14T12:00:00Z', [0, 1], 85),
    cast: [
      ['hyun-bin', 'Ri Jeong-hyeok'],
      ['son-ye-jin', 'Yoon Se-ri'],
      ['seo-ji-hye', 'Seo Dan'],
      ['kim-jung-hyun', 'Gu Seung-jun'],
    ],
    creators: ['Park Ji-eun (writer)', 'Lee Jung-hyo (director)'],
  }),
  drama({
    id: 'the-glory',
    title: 'The Glory',
    originalTitle: '더 글로리',
    year: 2022,
    endYear: 2023,
    status: 'completed',
    network: 'Netflix',
    streamingOn: ['Netflix'],
    genres: ['Thriller', 'Melodrama'],
    tags: ['revenge', 'slow burn'],
    synopsis: 'Years after brutal school abuse, a woman puts an elaborate plan of revenge into motion — one perpetrator at a time.',
    posterLocal: require('../assets/dramas/glory.png'),
    tone: '#2A2A2A',
    rating: 8.9,
    followerCount: 254_000,
    episodes: [...drop('the-glory', 1, 8, '2022-12-30T08:00:00Z', 50), ...drop('the-glory', 1, 8, '2023-03-10T08:00:00Z', 50).map((e) => ({ ...e, number: e.number + 8, id: `the-glory-s1e${e.number + 8}` }))],
    cast: [
      ['song-hye-kyo', 'Moon Dong-eun'],
      ['lee-do-hyun', 'Joo Yeo-jeong'],
      ['lim-ji-yeon', 'Park Yeon-jin'],
      ['jung-sung-il', 'Ha Do-yeong'],
    ],
    creators: ['Kim Eun-sook (writer)', 'Ahn Gil-ho (director)'],
  }),
  drama({
    id: 'business-proposal',
    title: 'Business Proposal',
    originalTitle: '사내맞선',
    year: 2022,
    status: 'completed',
    network: 'SBS',
    streamingOn: ['Netflix'],
    genres: ['Romance', 'Comedy'],
    tags: ['fake dating', 'office'],
    synopsis: 'She goes on a blind date pretending to be her friend. He turns out to be her CEO. It escalates.',
    posterLocal: require('../assets/dramas/proposal.png'),
    tone: '#4A2F3A',
    rating: 8.3,
    followerCount: 198_000,
    episodes: episodes('business-proposal', 1, 12, '2022-02-28T13:00:00Z', [0, 1], 65),
    cast: [
      ['ahn-hyo-seop', 'Kang Tae-moo'],
      ['kim-se-jeong', 'Shin Ha-ri'],
      ['kim-min-kyu', 'Cha Sung-hoon'],
      ['seol-in-ah', 'Jin Young-seo'],
    ],
  }),
  drama({
    id: 'squid-game',
    title: 'Squid Game',
    originalTitle: '오징어 게임',
    year: 2021,
    endYear: 2025,
    status: 'completed',
    network: 'Netflix',
    streamingOn: ['Netflix'],
    genres: ['Thriller', 'Action'],
    tags: ['survival', 'satire'],
    synopsis: 'Hundreds of cash-strapped players accept an invitation to compete in children’s games for a tempting prize — with deadly stakes.',
    tone: '#3F2A3A',
    rating: 8.6,
    followerCount: 402_000,
    episodes: [
      ...drop('squid-game', 1, 9, '2021-09-17T07:00:00Z', 55),
      ...drop('squid-game', 2, 7, '2024-12-26T08:00:00Z', 58),
      ...drop('squid-game', 3, 6, '2025-06-27T07:00:00Z', 60),
    ],
    cast: [
      ['lee-jung-jae', 'Seong Gi-hun'],
      ['lee-byung-hun', 'Front Man'],
      ['wi-ha-joon', 'Hwang Jun-ho'],
      ['park-hae-soo', 'Cho Sang-woo'],
      ['jung-ho-yeon', 'Kang Sae-byeok'],
    ],
    creators: ['Hwang Dong-hyuk (writer, director)'],
  }),
  drama({
    id: 'reply-1988',
    title: 'Reply 1988',
    originalTitle: '응답하라 1988',
    year: 2015,
    endYear: 2016,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix', 'Viki'],
    genres: ['Slice of life', 'Family', 'Youth'],
    tags: ['nostalgia', 'neighbourhood', 'comfort'],
    synopsis: 'Five families on one Ssangmun-dong alley in 1988 share meals, fights, first loves and everything in between.',
    tone: '#3F352A',
    rating: 9.3,
    followerCount: 221_000,
    episodes: episodes('reply-1988', 1, 20, '2015-11-06T10:50:00Z', [0, 1], 95, { 1: 'Hand in Hand', 18: 'Goodbye, First Love', 20: 'Goodbye, My Youth' }),
    cast: [
      ['lee-hye-ri', 'Sung Deok-sun'],
      ['park-bo-gum', 'Choi Taek'],
      ['ryu-jun-yeol', 'Kim Jung-hwan'],
      ['go-kyung-pyo', 'Sung Sun-woo'],
      ['lee-dong-hwi', 'Ryu Dong-ryong'],
    ],
  }),
  drama({
    id: 'my-mister',
    title: 'My Mister',
    originalTitle: '나의 아저씨',
    year: 2018,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix'],
    genres: ['Slice of life', 'Melodrama'],
    tags: ['healing', 'quiet'],
    synopsis: 'A weary engineer and a young woman surviving on almost nothing recognise each other’s pain — and slowly, help each other carry it.',
    tone: '#2A2F2A',
    rating: 9.2,
    followerCount: 134_000,
    episodes: episodes('my-mister', 1, 16, '2018-03-21T12:30:00Z', [0, 1], 90),
    cast: [
      ['lee-sun-kyun', 'Park Dong-hoon'],
      ['iu', 'Lee Ji-an'],
    ],
  }),
  drama({
    id: 'hospital-playlist',
    title: 'Hospital Playlist',
    originalTitle: '슬기로운 의사생활',
    year: 2020,
    endYear: 2021,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix'],
    genres: ['Medical', 'Slice of life', 'Comedy'],
    tags: ['friendship', 'band', 'comfort'],
    synopsis: 'Five doctors who have been friends since med school run a hospital by day and a terrible band by night.',
    tone: '#2A3A3A',
    rating: 9.0,
    followerCount: 176_000,
    episodes: [
      ...episodes('hospital-playlist', 1, 12, '2020-03-12T12:00:00Z', [0], 95),
      ...episodes('hospital-playlist', 2, 12, '2021-06-17T12:00:00Z', [0], 95),
    ],
    cast: [
      ['jo-jung-suk', 'Lee Ik-jun'],
      ['yoo-yeon-seok', 'Ahn Jeong-won'],
      ['jung-kyung-ho', 'Kim Jun-wan'],
      ['kim-dae-myung', 'Yang Seok-hyeong'],
      ['jeon-mi-do', 'Chae Song-hwa'],
    ],
  }),
  drama({
    id: 'vincenzo',
    title: 'Vincenzo',
    originalTitle: '빈센조',
    year: 2021,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix'],
    genres: ['Crime', 'Comedy', 'Action'],
    tags: ['mafia', 'dark comedy'],
    synopsis: 'A Korean-Italian mafia consigliere returns to Seoul and uses villainy to fight villains.',
    tone: '#3A2A2A',
    rating: 8.7,
    followerCount: 189_000,
    episodes: episodes('vincenzo', 1, 20, '2021-02-20T12:00:00Z', [0, 1], 80),
    cast: [
      ['song-joong-ki', 'Vincenzo Cassano'],
      ['jeon-yeo-been', 'Hong Cha-young'],
      ['ok-taec-yeon', 'Jang Jun-woo'],
    ],
  }),
  drama({
    id: 'signal',
    title: 'Signal',
    originalTitle: '시그널',
    year: 2016,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix', 'Viki'],
    genres: ['Crime', 'Thriller', 'Mystery'],
    tags: ['time', 'cold cases'],
    synopsis: 'A walkie-talkie connects a profiler in 2015 with a detective in 1989 — and every solved case rewrites the present.',
    tone: '#2A3340',
    rating: 9.1,
    followerCount: 121_000,
    episodes: episodes('signal', 1, 16, '2016-01-22T11:00:00Z', [0, 1], 70),
    cast: [
      ['lee-je-hoon', 'Park Hae-young'],
      ['kim-hye-soo', 'Cha Soo-hyun'],
      ['cho-jin-woong', 'Lee Jae-han'],
    ],
  }),
  drama({
    id: 'mr-sunshine',
    title: 'Mr. Sunshine',
    originalTitle: '미스터 션샤인',
    year: 2018,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix'],
    genres: ['Historical', 'Romance', 'Melodrama'],
    tags: ['1900s', 'epic'],
    synopsis: 'A boy born a slave returns to Joseon as a US Marine officer and falls for a noblewoman who is secretly a sniper for the resistance.',
    tone: '#3A332A',
    rating: 9.0,
    followerCount: 143_000,
    episodes: episodes('mr-sunshine', 1, 24, '2018-07-07T12:00:00Z', [0, 1], 80),
    cast: [
      ['lee-byung-hun', 'Eugene Choi'],
      ['kim-tae-ri', 'Go Ae-shin'],
      ['yoo-yeon-seok', 'Gu Dong-mae'],
      ['kim-min-jung', 'Kudo Hina'],
      ['byun-yo-han', 'Kim Hui-seong'],
    ],
    creators: ['Kim Eun-sook (writer)', 'Lee Eung-bok (director)'],
  }),
  drama({
    id: 'twenty-five-twenty-one',
    title: 'Twenty-Five Twenty-One',
    originalTitle: '스물다섯 스물하나',
    year: 2022,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix'],
    genres: ['Youth', 'Romance', 'Slice of life'],
    tags: ['1998', 'fencing', 'bittersweet'],
    synopsis: 'In the wake of the IMF crisis, a teenage fencer and a young man who lost everything find each other — at exactly the wrong time.',
    tone: '#2A3A33',
    rating: 8.6,
    followerCount: 167_000,
    episodes: episodes('twenty-five-twenty-one', 1, 16, '2022-02-12T12:10:00Z', [0, 1], 75),
    cast: [
      ['kim-tae-ri', 'Na Hee-do'],
      ['nam-joo-hyuk', 'Baek Yi-jin'],
      ['bona', 'Go Yu-rim'],
    ],
  }),
  drama({
    id: 'extraordinary-attorney-woo',
    title: 'Extraordinary Attorney Woo',
    originalTitle: '이상한 변호사 우영우',
    year: 2022,
    status: 'completed',
    network: 'ENA',
    streamingOn: ['Netflix'],
    genres: ['Legal', 'Slice of life'],
    tags: ['whales', 'case of the week'],
    synopsis: 'A brilliant rookie attorney on the autism spectrum takes on cases her colleagues cannot see clearly.',
    tone: '#2A3A40',
    rating: 8.8,
    followerCount: 174_000,
    episodes: episodes('extraordinary-attorney-woo', 1, 16, '2022-06-29T12:00:00Z', [0, 1], 70),
    cast: [
      ['park-eun-bin', 'Woo Young-woo'],
      ['kang-tae-oh', 'Lee Jun-ho'],
      ['kang-ki-young', 'Jung Myung-seok'],
    ],
  }),
  drama({
    id: 'queen-of-tears',
    title: 'Queen of Tears',
    originalTitle: '눈물의 여왕',
    year: 2024,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix'],
    genres: ['Romance', 'Melodrama', 'Comedy'],
    tags: ['marriage', 'chaebol'],
    synopsis: 'A department-store heiress and her husband from a village orchard are on the brink of divorce when a diagnosis changes everything.',
    tone: '#3A2A33',
    rating: 8.5,
    followerCount: 231_000,
    episodes: episodes('queen-of-tears', 1, 16, '2024-03-09T12:10:00Z', [0, 1], 80),
    cast: [
      ['kim-soo-hyun', 'Baek Hyun-woo'],
      ['kim-ji-won', 'Hong Hae-in'],
      ['park-sung-hoon', 'Yoon Eun-sung'],
    ],
  }),
  drama({
    id: 'moving',
    title: 'Moving',
    originalTitle: '무빙',
    year: 2023,
    status: 'completed',
    network: 'Disney+',
    streamingOn: ['Disney+', 'Hulu'],
    genres: ['Action', 'Fantasy', 'Youth'],
    tags: ['superpowers', 'parents'],
    synopsis: 'Teenagers hiding superpowers — and the parents who hid theirs first — are hunted by the agency that made them.',
    tone: '#2A2A3A',
    rating: 9.0,
    followerCount: 158_000,
    episodes: [...drop('moving', 1, 7, '2023-08-09T07:00:00Z', 60), ...episodes('moving', 1, 13, '2023-08-16T07:00:00Z', [0], 60).map((e) => ({ ...e, number: e.number + 7, id: `moving-s1e${e.number + 7}` }))],
    cast: [
      ['ryu-seung-ryong', 'Jang Ju-won'],
      ['han-hyo-joo', 'Lee Mi-hyun'],
      ['zo-in-sung', 'Kim Doo-sik'],
      ['lee-jung-ha', 'Kim Bong-seok'],
      ['go-youn-jung', 'Jang Hui-soo'],
    ],
  }),
  drama({
    id: 'lovely-runner',
    title: 'Lovely Runner',
    originalTitle: '선재 업고 튀어',
    year: 2024,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Viki'],
    genres: ['Romance', 'Fantasy', 'Youth'],
    tags: ['time travel', 'idol'],
    synopsis: 'A devoted fan travels back to 2008 to save the idol who once saved her.',
    tone: '#3F2A3A',
    rating: 8.7,
    followerCount: 203_000,
    episodes: episodes('lovely-runner', 1, 16, '2024-04-08T11:50:00Z', [0, 1], 70),
    cast: [
      ['byeon-woo-seok', 'Ryu Sun-jae'],
      ['kim-hye-yoon', 'Im Sol'],
    ],
  }),
  drama({
    id: 'when-life-gives-you-tangerines',
    title: 'When Life Gives You Tangerines',
    originalTitle: '폭싹 속았수다',
    year: 2025,
    status: 'completed',
    network: 'Netflix',
    streamingOn: ['Netflix'],
    genres: ['Slice of life', 'Romance', 'Family'],
    tags: ['Jeju', 'generations', 'tearjerker'],
    synopsis: 'Across four seasons and four decades on Jeju, a fiery girl and the boy who never stopped standing beside her build a life.',
    tone: '#3F3A2A',
    rating: 9.2,
    followerCount: 246_000,
    episodes: [...drop('when-life-gives-you-tangerines', 1, 4, '2025-03-07T08:00:00Z', 60), ...drop('when-life-gives-you-tangerines', 1, 4, '2025-03-14T08:00:00Z', 60).map((e) => ({ ...e, number: e.number + 4, id: `when-life-gives-you-tangerines-s1e${e.number + 4}` })), ...drop('when-life-gives-you-tangerines', 1, 4, '2025-03-21T08:00:00Z', 60).map((e) => ({ ...e, number: e.number + 8, id: `when-life-gives-you-tangerines-s1e${e.number + 8}` })), ...drop('when-life-gives-you-tangerines', 1, 4, '2025-03-28T08:00:00Z', 60).map((e) => ({ ...e, number: e.number + 12, id: `when-life-gives-you-tangerines-s1e${e.number + 12}` }))],
    cast: [
      ['iu', 'Oh Ae-sun'],
      ['park-bo-gum', 'Yang Gwan-sik'],
      ['moon-so-ri', 'Oh Ae-sun (later years)'],
      ['park-hae-joon', 'Yang Gwan-sik (later years)'],
    ],
  }),
  drama({
    id: 'hometown-cha-cha-cha',
    title: 'Hometown Cha-Cha-Cha',
    originalTitle: '갯마을 차차차',
    year: 2021,
    status: 'completed',
    network: 'tvN',
    streamingOn: ['Netflix'],
    genres: ['Romance', 'Comedy', 'Slice of life'],
    tags: ['seaside', 'healing', 'comfort'],
    synopsis: 'A city dentist opens a clinic in a seaside village and keeps running into the jack-of-all-trades everyone calls Chief Hong.',
    tone: '#2A3A3F',
    rating: 8.6,
    followerCount: 171_000,
    episodes: episodes('hometown-cha-cha-cha', 1, 16, '2021-08-28T12:00:00Z', [0, 1], 75),
    cast: [
      ['shin-min-a', 'Yoon Hye-jin'],
      ['kim-seon-ho', 'Hong Du-sik'],
    ],
  }),
];

// ---------- actors ----------
const A: [string, string, string, string?][] = [
  ['gong-yoo', 'Gong Yoo', '공유', 'Actor known for Train to Busan, Coffee Prince and Goblin.'],
  ['kim-go-eun', 'Kim Go-eun', '김고은', 'Film-trained actor whose range runs from Goblin to Exhuma.'],
  ['lee-dong-wook', 'Lee Dong-wook', '이동욱', 'The Grim Reaper himself; also Tale of the Nine-Tailed.'],
  ['yoo-in-na', 'Yoo In-na', '유인나', 'Sunny in Goblin; Touch Your Heart.'],
  ['yook-sung-jae', 'Yook Sung-jae', '육성재', 'BTOB vocalist and actor.'],
  ['hyun-bin', 'Hyun Bin', '현빈', 'Secret Garden, Crash Landing on You, Harbin.'],
  ['son-ye-jin', 'Son Ye-jin', '손예진', 'Something in the Rain, Crash Landing on You.'],
  ['seo-ji-hye', 'Seo Ji-hye', '서지혜', 'Seo Dan in Crash Landing on You.'],
  ['kim-jung-hyun', 'Kim Jung-hyun', '김정현', 'Gu Seung-jun in Crash Landing on You.'],
  ['song-hye-kyo', 'Song Hye-kyo', '송혜교', 'Autumn in My Heart, Descendants of the Sun, The Glory.'],
  ['lee-do-hyun', 'Lee Do-hyun', '이도현', '18 Again, The Good Bad Mother, The Glory.'],
  ['lim-ji-yeon', 'Lim Ji-yeon', '임지연', 'Park Yeon-jin in The Glory; Lies Hidden in My Garden.'],
  ['jung-sung-il', 'Jung Sung-il', '정성일', 'Ha Do-yeong in The Glory.'],
  ['ahn-hyo-seop', 'Ahn Hyo-seop', '안효섭', 'Dr. Romantic 2, Business Proposal, A Time Called You.'],
  ['kim-se-jeong', 'Kim Se-jeong', '김세정', 'Singer-actor; The Uncanny Counter, Business Proposal.'],
  ['kim-min-kyu', 'Kim Min-kyu', '김민규', 'Cha Sung-hoon in Business Proposal.'],
  ['seol-in-ah', 'Seol In-ah', '설인아', 'Jin Young-seo in Business Proposal.'],
  ['lee-jung-jae', 'Lee Jung-jae', '이정재', 'Emmy-winning lead of Squid Game.'],
  ['lee-byung-hun', 'Lee Byung-hun', '이병헌', 'Mr. Sunshine, Squid Game, Concrete Utopia.'],
  ['wi-ha-joon', 'Wi Ha-joon', '위하준', 'Squid Game, Little Women, The Worst of Evil.'],
  ['park-hae-soo', 'Park Hae-soo', '박해수', 'Prison Playbook, Squid Game.'],
  ['jung-ho-yeon', 'Jung Ho-yeon', '정호연', 'Model turned actor; Squid Game.'],
  ['lee-hye-ri', 'Lee Hye-ri', '이혜리', "Girl's Day member; Reply 1988."],
  ['park-bo-gum', 'Park Bo-gum', '박보검', 'Reply 1988, Love in the Moonlight, When Life Gives You Tangerines.'],
  ['ryu-jun-yeol', 'Ryu Jun-yeol', '류준열', 'Reply 1988, Lost.'],
  ['go-kyung-pyo', 'Go Kyung-pyo', '고경표', 'Reply 1988, Chicago Typewriter.'],
  ['lee-dong-hwi', 'Lee Dong-hwi', '이동휘', 'Reply 1988, Big Bet.'],
  ['lee-sun-kyun', 'Lee Sun-kyun', '이선균', 'My Mister, Parasite (1975–2023).'],
  ['iu', 'IU', '이지은', 'Singer-songwriter and actor; My Mister, Hotel del Luna, When Life Gives You Tangerines.'],
  ['jo-jung-suk', 'Jo Jung-suk', '조정석', 'Hospital Playlist, Captivating the King.'],
  ['yoo-yeon-seok', 'Yoo Yeon-seok', '유연석', 'Reply 1994, Mr. Sunshine, Hospital Playlist.'],
  ['jung-kyung-ho', 'Jung Kyung-ho', '정경호', 'Prison Playbook, Hospital Playlist, Crash Course in Romance.'],
  ['kim-dae-myung', 'Kim Dae-myung', '김대명', 'Misaeng, Hospital Playlist.'],
  ['jeon-mi-do', 'Jeon Mi-do', '전미도', 'Musical star; Hospital Playlist, Thirty-Nine.'],
  ['song-joong-ki', 'Song Joong-ki', '송중기', 'Descendants of the Sun, Vincenzo, Reborn Rich.'],
  ['jeon-yeo-been', 'Jeon Yeo-been', '전여빈', 'Vincenzo, Glitch.'],
  ['ok-taec-yeon', 'Ok Taec-yeon', '옥택연', '2PM member; Vincenzo.'],
  ['lee-je-hoon', 'Lee Je-hoon', '이제훈', 'Signal, Taxi Driver.'],
  ['kim-hye-soo', 'Kim Hye-soo', '김혜수', 'Signal, Under the Queen’s Umbrella.'],
  ['cho-jin-woong', 'Cho Jin-woong', '조진웅', 'Signal, The Handmaiden.'],
  ['kim-tae-ri', 'Kim Tae-ri', '김태리', 'The Handmaiden, Mr. Sunshine, Twenty-Five Twenty-One.'],
  ['kim-min-jung', 'Kim Min-jung', '김민정', 'Kudo Hina in Mr. Sunshine.'],
  ['byun-yo-han', 'Byun Yo-han', '변요한', 'Misaeng, Mr. Sunshine.'],
  ['nam-joo-hyuk', 'Nam Joo-hyuk', '남주혁', 'Start-Up, Twenty-Five Twenty-One.'],
  ['bona', 'Bona', '보나', 'WJSN member; Twenty-Five Twenty-One.'],
  ['park-eun-bin', 'Park Eun-bin', '박은빈', 'The King’s Affection, Extraordinary Attorney Woo.'],
  ['kang-tae-oh', 'Kang Tae-oh', '강태오', 'Extraordinary Attorney Woo.'],
  ['kang-ki-young', 'Kang Ki-young', '강기영', 'Extraordinary Attorney Woo, Sweet Home.'],
  ['kim-soo-hyun', 'Kim Soo-hyun', '김수현', 'My Love from the Star, It’s Okay to Not Be Okay, Queen of Tears.'],
  ['kim-ji-won', 'Kim Ji-won', '김지원', 'Fight for My Way, My Liberation Notes, Queen of Tears.'],
  ['park-sung-hoon', 'Park Sung-hoon', '박성훈', 'The Glory, Queen of Tears, Squid Game 2.'],
  ['ryu-seung-ryong', 'Ryu Seung-ryong', '류승룡', 'Kingdom, Moving.'],
  ['han-hyo-joo', 'Han Hyo-joo', '한효주', 'W, Moving.'],
  ['zo-in-sung', 'Zo In-sung', '조인성', 'That Winter the Wind Blows, Moving.'],
  ['lee-jung-ha', 'Lee Jung-ha', '이정하', 'Kim Bong-seok in Moving.'],
  ['go-youn-jung', 'Go Youn-jung', '고윤정', 'Alchemy of Souls, Moving, Resident Playbook.'],
  ['byeon-woo-seok', 'Byeon Woo-seok', '변우석', 'Lovely Runner.'],
  ['kim-hye-yoon', 'Kim Hye-yoon', '김혜윤', 'Sky Castle, Extraordinary You, Lovely Runner.'],
  ['moon-so-ri', 'Moon So-ri', '문소리', 'Oasis, Queenmaker, When Life Gives You Tangerines.'],
  ['park-hae-joon', 'Park Hae-joon', '박해준', 'The World of the Married, When Life Gives You Tangerines.'],
  ['shin-min-a', 'Shin Min-a', '신민아', 'My Girlfriend Is a Gumiho, Hometown Cha-Cha-Cha.'],
  ['kim-seon-ho', 'Kim Seon-ho', '김선호', 'Start-Up, Hometown Cha-Cha-Cha.'],
  ['seo-kang-joon', 'Seo Kang-joon', '서강준', 'Cheese in the Trap, Are You Human?, A Love Other Than Yours.'],
  ['ahn-eun-jin', 'Ahn Eun-jin', '안은진', 'Hospital Playlist, My Dearest, A Love Other Than Yours.'],
  ['ji-chang-wook', 'Ji Chang-wook', '지창욱', 'Healer, The K2, The Scandal.'],
  ['nana', 'Nana', '나나', 'After School member; Mask Girl, The Scandal.'],
  ['jung-woo-sung', 'Jung Woo-sung', '정우성', 'Beat, Asura, Made in Korea.'],
];

export const ACTORS: Actor[] = A.map(([id, name, koreanName, bio]) => {
  const knownFor = DRAMAS.filter((d) => d.cast.some((c) => c.actorId === id))
    .sort((x, y) => y.followerCount - x.followerCount)
    .map((d) => d.id);
  const seed = id.split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  return { id, name, koreanName, bio, knownFor, followerCount: 8_000 + (seed % 90) * 2_100 };
});

// ---------- users ----------
export const ME_ID = 'me';
export const USERS: User[] = [
  {
    id: ME_ID,
    handle: 'minapark',
    displayName: 'Mina Park',
    avatarUrl: 'https://i.pravatar.cc/240?img=47',
    bio: 'Collecting scenes that stay with me. Lagos ↔ Seoul, in spirit.',
    favoriteGenres: ['Romance', 'Slice of life', 'Fantasy'],
    favoriteDramaIds: ['goblin', 'reply-1988', 'my-mister', 'crash-landing-on-you'],
    followers: 1_284,
    following: 342,
    joinedAt: at('2026-02-11T10:00:00Z'),
  },
  { id: 'jae', handle: 'jaeonair', displayName: 'Jae', avatarUrl: 'https://i.pravatar.cc/240?img=12', bio: 'One more episode. Always one more.', favoriteGenres: ['Thriller', 'Crime'], favoriteDramaIds: ['signal', 'the-glory', 'moving'], followers: 842, following: 201, joinedAt: at('2026-03-02T10:00:00Z') },
  { id: 'sora', handle: 'sorakim', displayName: 'Sora Kim', avatarUrl: 'https://i.pravatar.cc/240?img=32', bio: 'Romance, revenge, repeat. Recaps every Sunday.', favoriteGenres: ['Romance', 'Melodrama'], favoriteDramaIds: ['queen-of-tears', 'the-glory', 'lovely-runner'], followers: 4_210, following: 118, joinedAt: at('2026-01-20T10:00:00Z'), verified: true },
  { id: 'dan', handle: 'danwatches', displayName: 'Daniel Oh', avatarUrl: 'https://i.pravatar.cc/240?img=68', bio: 'Historical dramas and long walks to the fridge.', favoriteGenres: ['Historical', 'Action'], favoriteDramaIds: ['mr-sunshine', 'vincenzo'], followers: 611, following: 390, joinedAt: at('2026-04-14T10:00:00Z') },
  { id: 'yuna', handle: 'yunaverse', displayName: 'Yuna Choi', avatarUrl: 'https://i.pravatar.cc/240?img=25', bio: 'I cry at OSTs. Currently: everything Kim Eun-sook.', favoriteGenres: ['Fantasy', 'Romance'], favoriteDramaIds: ['goblin', 'mr-sunshine', 'lovely-runner'], followers: 2_930, following: 240, joinedAt: at('2026-02-28T10:00:00Z') },
  { id: 'tobi', handle: 'tobi_kdrama', displayName: 'Tobi Adeyemi', avatarUrl: 'https://i.pravatar.cc/240?img=59', bio: 'Lagos. Slice-of-life evangelist. Reply 1988 changed my life.', favoriteGenres: ['Slice of life', 'Family', 'Comedy'], favoriteDramaIds: ['reply-1988', 'hospital-playlist', 'when-life-gives-you-tangerines'], followers: 1_502, following: 520, joinedAt: at('2026-03-19T10:00:00Z') },
  { id: 'lena', handle: 'lenaf', displayName: 'Lena Fischer', avatarUrl: 'https://i.pravatar.cc/240?img=44', bio: 'Theories, timelines, spreadsheets.', favoriteGenres: ['Mystery', 'Thriller', 'Sci-fi'], favoriteDramaIds: ['signal', 'squid-game', 'moving'], followers: 3_388, following: 77, joinedAt: at('2026-01-05T10:00:00Z') },
  { id: 'haru', handle: 'haru.rewinds', displayName: 'Haru Sato', avatarUrl: 'https://i.pravatar.cc/240?img=15', bio: 'Rewatching the classics so you don’t have to (you should).', favoriteGenres: ['Melodrama', 'Slice of life'], favoriteDramaIds: ['my-mister', 'twenty-five-twenty-one'], followers: 972, following: 305, joinedAt: at('2026-05-01T10:00:00Z') },
  { id: 'priv', handle: 'quietwatcher', displayName: 'Quiet Watcher', bio: 'Private account.', favoriteGenres: [], favoriteDramaIds: [], followers: 12, following: 40, joinedAt: at('2026-06-01T10:00:00Z'), isPrivate: true },
];

// ---------- posts ----------
const P = (p: Omit<Post, 'hashtags' | 'mentions' | 'reactions' | 'commentCount' | 'saveCount' | 'shareCount' | 'spoiler' | 'context'> & Partial<Post>): Post => ({
  hashtags: [],
  mentions: [],
  reactions: emptyReactions(),
  commentCount: 0,
  saveCount: 0,
  shareCount: 0,
  spoiler: 'none',
  context: {},
  ...p,
});

export const POSTS: Post[] = [
  P({
    id: 'p-alo-ep3-live',
    type: 'reaction',
    authorId: 'yuna',
    createdAt: ago(6),
    body: 'That last shot on the pier. I am not okay. #ALoveOtherThanYours',
    spoiler: 'episode',
    context: { dramaId: 'a-love-other-than-yours', season: 1, episode: 3 },
    hashtags: ['ALoveOtherThanYours'],
    reactions: rx({ loved: 88, cried: 142, swooned: 31 }),
    commentCount: 19,
    saveCount: 4,
  }),
  P({
    id: 'p-alo-ep3-disc',
    type: 'discussion',
    authorId: 'sora',
    createdAt: ago(22),
    title: 'Episode 3 — the letter was never sent, right?',
    kind: 'theory',
    body: 'Rewatch the drawer scene at 41:10. The envelope is sealed but there is no stamp. I think the whole "you never wrote" argument is built on a letter he still has. Which would make the ending of ep 4 land very differently.',
    spoiler: 'episode',
    context: { dramaId: 'a-love-other-than-yours', season: 1, episode: 3 },
    reactions: rx({ loved: 210, screamed: 64, cried: 12 }),
    commentCount: 47,
    saveCount: 38,
    shareCount: 9,
  }),
  P({
    id: 'p-scandal-ending',
    type: 'discussion',
    authorId: 'dan',
    createdAt: ago(3 * H),
    title: 'The Scandal ending — better or worse than the film?',
    kind: 'ending',
    body: 'Finished all 8 in one sitting. The final episode makes a choice the 2003 film refused to make, and I think it is the right one for a series. Spoilers for the whole thing below.',
    spoiler: 'ending',
    context: { dramaId: 'the-scandal', season: 1, episode: 8 },
    reactions: rx({ loved: 156, screamed: 40, furious: 22, cried: 71 }),
    commentCount: 83,
    saveCount: 27,
    shareCount: 14,
  }),
  P({
    id: 'p-scandal-review',
    type: 'review',
    authorId: 'sora',
    createdAt: ago(5 * H),
    rating: 8,
    verdict: 'Gorgeous, cruel, and Son Ye-jin has never been colder.',
    body: 'Untold Scandal was always going to be a hard remake — the film is beloved and the story is thin for eight hours. The series solves it by giving Lady Cho an interior life and letting the seduction take its time. Costume and lighting are the best Netflix Korea has produced. Two episodes in the middle sag. The last twenty minutes justify everything.',
    spoiler: 'none',
    context: { dramaId: 'the-scandal' },
    reactions: rx({ loved: 302, swooned: 88 }),
    commentCount: 36,
    saveCount: 91,
    shareCount: 21,
  }),
  P({
    id: 'p-scandal-first',
    type: 'reaction',
    authorId: 'tobi',
    createdAt: ago(9 * H),
    body: 'Ji Chang-wook playing a villain you root against and for at the same time. Two episodes in and already ruined.',
    spoiler: 'none',
    context: { dramaId: 'the-scandal', season: 1, episode: 2, actorIds: ['ji-chang-wook'] },
    reactions: rx({ loved: 64, swooned: 120, laughed: 8 }),
    commentCount: 11,
  }),
  P({
    id: 'p-mik-ep2',
    type: 'reaction',
    authorId: 'jae',
    createdAt: ago(2 * D + 4 * H),
    body: 'Made in Korea S2 ep 2: the ledger reveal is the best written scene this year. Hyun Bin did that with one eyebrow.',
    spoiler: 'episode',
    context: { dramaId: 'made-in-korea', season: 2, episode: 2, actorIds: ['hyun-bin'] },
    reactions: rx({ loved: 97, screamed: 33 }),
    commentCount: 14,
    saveCount: 6,
  }),
  P({
    id: 'p-goblin-rewatch',
    type: 'post',
    authorId: ME_ID,
    createdAt: ago(1 * D + 2 * H),
    body: 'Annual Goblin rewatch, night one. The buckwheat field still wins. Nine years and the show has not aged a single day.',
    images: [require('../assets/ui/post-01.png')],
    spoiler: 'none',
    context: { dramaId: 'goblin' },
    hashtags: ['rewatch'],
    reactions: rx({ loved: 284, swooned: 40, cried: 12 }),
    commentCount: 32,
    saveCount: 41,
    shareCount: 3,
  }),
  P({
    id: 'p-goblin-ending',
    type: 'discussion',
    authorId: 'yuna',
    createdAt: ago(3 * D),
    title: 'Is the Goblin ending actually happy? (ending spoilers)',
    kind: 'ending',
    body: 'Every rewatch I move a little further from “happy”. He waited centuries; she gets one life at a time. Convince me the last scene is a kindness and not a curse with better lighting.',
    spoiler: 'ending',
    context: { dramaId: 'goblin', season: 1, episode: 16 },
    reactions: rx({ loved: 410, cried: 188, furious: 31 }),
    commentCount: 126,
    saveCount: 74,
    shareCount: 18,
  }),
  P({
    id: 'p-cloy-recs',
    type: 'post',
    authorId: 'jae',
    createdAt: ago(4 * D),
    body: 'Need a new drama with this exact emotional damage. Recommendations that are not Goblin, please.',
    spoiler: 'none',
    context: { dramaId: 'crash-landing-on-you' },
    reactions: rx({ loved: 119, laughed: 40 }),
    commentCount: 58,
    saveCount: 12,
  }),
  P({
    id: 'p-glory-pacing',
    type: 'post',
    authorId: 'sora',
    createdAt: ago(5 * D),
    body: 'The pacing in The Glory is ridiculously satisfying. Every episode ends exactly one beat after you think it will.',
    images: [require('../assets/ui/post-02.png')],
    spoiler: 'none',
    context: { dramaId: 'the-glory' },
    reactions: rx({ loved: 431, screamed: 57 }),
    commentCount: 57,
    saveCount: 88,
    shareCount: 12,
  }),
  P({
    id: 'p-glory-ep8',
    type: 'reaction',
    authorId: 'lena',
    createdAt: ago(6 * D),
    body: 'The part 1 cliffhanger. THE GO BOARD. Nobody warned me.',
    spoiler: 'episode',
    context: { dramaId: 'the-glory', season: 1, episode: 8 },
    reactions: rx({ screamed: 210, loved: 40 }),
    commentCount: 21,
  }),
  P({
    id: 'p-reply-review',
    type: 'review',
    authorId: 'tobi',
    createdAt: ago(7 * D),
    rating: 10,
    verdict: 'The warmest twenty hours of television ever made.',
    body: 'I put this off for years because "family drama, 20 episodes, 90 minutes each" sounded like homework. It is the opposite. It is a neighbourhood you get to live in. The husband mystery is the least interesting thing about it and I still gasped. Watch it with people you love.',
    spoiler: 'none',
    context: { dramaId: 'reply-1988' },
    reactions: rx({ loved: 522, cried: 130, laughed: 44 }),
    commentCount: 64,
    saveCount: 140,
    shareCount: 33,
  }),
  P({
    id: 'p-reply-ep18',
    type: 'reaction',
    authorId: 'haru',
    createdAt: ago(8 * D),
    body: 'Episode 18 of Reply 1988. Jung-hwan at the traffic lights. I need a moment.',
    spoiler: 'episode',
    context: { dramaId: 'reply-1988', season: 1, episode: 18 },
    reactions: rx({ cried: 340, loved: 90 }),
    commentCount: 29,
  }),
  P({
    id: 'p-mymister-rec',
    type: 'recommendation',
    authorId: 'haru',
    createdAt: ago(9 * D),
    body: 'If Reply 1988 held your hand, My Mister will sit next to you in silence until you feel better. Slower, sadder, and the most humane thing on TV. Give it three episodes.',
    spoiler: 'none',
    context: { dramaId: 'my-mister', secondaryDramaId: 'reply-1988' },
    reactions: rx({ loved: 268, cried: 52 }),
    commentCount: 23,
    saveCount: 97,
    shareCount: 15,
  }),
  P({
    id: 'p-qot-rec',
    type: 'recommendation',
    authorId: 'sora',
    createdAt: ago(10 * D),
    body: 'Liked Crash Landing on You? Queen of Tears is the same writer, the same chaos, and a marriage instead of a meet-cute. Kim Ji-won is doing career-best work.',
    spoiler: 'none',
    context: { dramaId: 'queen-of-tears', secondaryDramaId: 'crash-landing-on-you', actorIds: ['kim-ji-won'] },
    reactions: rx({ loved: 190, swooned: 60 }),
    commentCount: 17,
    saveCount: 61,
  }),
  P({
    id: 'p-moving-theory',
    type: 'discussion',
    authorId: 'lena',
    createdAt: ago(11 * D),
    title: 'Moving: the parents’ timeline, mapped',
    kind: 'theory',
    body: 'I built the full 1994–2018 timeline for the agency arc. Two scenes in ep 12 cannot both be true unless Doo-sik went north twice. Sheet in the comments.',
    spoiler: 'season',
    context: { dramaId: 'moving', season: 1, episode: 12 },
    reactions: rx({ loved: 88, screamed: 25 }),
    commentCount: 41,
    saveCount: 33,
  }),
  P({
    id: 'p-25-21-furious',
    type: 'reaction',
    authorId: 'yuna',
    createdAt: ago(12 * D),
    body: 'Twenty-Five Twenty-One ending. Still furious. Still crying. Still recommending it.',
    spoiler: 'ending',
    context: { dramaId: 'twenty-five-twenty-one', season: 1, episode: 16 },
    reactions: rx({ furious: 150, cried: 220, loved: 60 }),
    commentCount: 77,
  }),
  P({
    id: 'p-bp-comfort',
    type: 'post',
    authorId: 'tobi',
    createdAt: ago(13 * D),
    body: 'Business Proposal is the drama equivalent of a heated blanket. Zero stakes, maximum joy. Kim Se-jeong’s comic timing deserves awards.',
    spoiler: 'none',
    context: { dramaId: 'business-proposal', actorIds: ['kim-se-jeong'] },
    reactions: rx({ loved: 200, laughed: 140, swooned: 30 }),
    commentCount: 22,
    saveCount: 15,
  }),
  P({
    id: 'p-woo-q',
    type: 'discussion',
    authorId: 'dan',
    createdAt: ago(14 * D),
    title: 'Which Attorney Woo case would you defend differently?',
    kind: 'question',
    body: 'Rewatching for the whales. The ep 3 case still feels unresolved to me. Curious what people who actually practise law think.',
    spoiler: 'season',
    context: { dramaId: 'extraordinary-attorney-woo', season: 1, episode: 3 },
    reactions: rx({ loved: 66 }),
    commentCount: 30,
  }),
  P({
    id: 'p-signal-rec',
    type: 'recommendation',
    authorId: 'jae',
    createdAt: ago(15 * D),
    body: 'Finished Squid Game and want something smarter? Signal. Sixteen episodes, no wasted scenes, an ending that trusts you.',
    spoiler: 'none',
    context: { dramaId: 'signal', secondaryDramaId: 'squid-game' },
    reactions: rx({ loved: 144 }),
    commentCount: 12,
    saveCount: 44,
  }),
  P({
    id: 'p-lr-swoon',
    type: 'reaction',
    authorId: 'sora',
    createdAt: ago(16 * D),
    body: 'Byeon Woo-seok in the rain in ep 5. That is the post.',
    spoiler: 'episode',
    context: { dramaId: 'lovely-runner', season: 1, episode: 5, actorIds: ['byeon-woo-seok'] },
    reactions: rx({ swooned: 410, loved: 100 }),
    commentCount: 40,
  }),
  P({
    id: 'p-tangerines-review',
    type: 'review',
    authorId: ME_ID,
    createdAt: ago(18 * D),
    rating: 9,
    verdict: 'Four seasons, four decades, one long exhale.',
    body: 'Structured like a memoir and shot like a memory. IU and Park Bo-gum carry the first half; Moon So-ri and Park Hae-joon carry you out. The tangerine motif is not subtle and it does not need to be. Bring tissues, then bring more.',
    spoiler: 'none',
    context: { dramaId: 'when-life-gives-you-tangerines' },
    reactions: rx({ loved: 156, cried: 88 }),
    commentCount: 18,
    saveCount: 52,
  }),
  P({
    id: 'p-hp-band',
    type: 'post',
    authorId: 'tobi',
    createdAt: ago(20 * D),
    body: 'Hospital Playlist band nights are the purest thing on television. Which cover is the best? Wrong answers only.',
    spoiler: 'none',
    context: { dramaId: 'hospital-playlist' },
    reactions: rx({ laughed: 90, loved: 120 }),
    commentCount: 45,
  }),
  // shorts
  P({
    id: 's-1',
    type: 'short',
    authorId: 'yuna',
    createdAt: ago(3 * H),
    body: 'Every Kim Eun-sook slow-motion walk, ranked in 40 seconds.',
    video: { url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', duration: 15 },
    spoiler: 'none',
    context: { dramaId: 'goblin' },
    hashtags: ['edit', 'KimEunSook'],
    reactions: rx({ loved: 1_240, laughed: 300 }),
    commentCount: 86,
    saveCount: 210,
    shareCount: 64,
  }),
  P({
    id: 's-2',
    type: 'short',
    authorId: 'sora',
    createdAt: ago(7 * H),
    body: 'The Scandal costume details you missed (no spoilers).',
    video: { url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', duration: 15 },
    spoiler: 'none',
    context: { dramaId: 'the-scandal' },
    hashtags: ['TheScandal', 'hanbok'],
    reactions: rx({ loved: 860, swooned: 420 }),
    commentCount: 54,
    saveCount: 330,
    shareCount: 91,
  }),
  P({
    id: 's-3',
    type: 'short',
    authorId: 'tobi',
    createdAt: ago(1 * D),
    body: 'Reply 1988 dinner scenes as a mood board.',
    video: { url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', duration: 60 },
    spoiler: 'none',
    context: { dramaId: 'reply-1988' },
    hashtags: ['comfortwatch'],
    reactions: rx({ loved: 540, cried: 90 }),
    commentCount: 31,
    saveCount: 120,
  }),
  P({
    id: 's-4',
    type: 'short',
    authorId: 'lena',
    createdAt: ago(2 * D),
    body: 'Moving ep 12 timeline in 45 seconds — season spoilers.',
    video: { url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', duration: 15 },
    spoiler: 'season',
    context: { dramaId: 'moving', season: 1, episode: 12 },
    reactions: rx({ screamed: 210, loved: 180 }),
    commentCount: 40,
    saveCount: 66,
  }),
  P({
    id: 's-5',
    type: 'short',
    authorId: 'haru',
    createdAt: ago(3 * D),
    body: 'Lovely Runner — the umbrella, three different lighting setups.',
    video: { url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', duration: 15 },
    spoiler: 'none',
    context: { dramaId: 'lovely-runner', actorIds: ['byeon-woo-seok'] },
    reactions: rx({ swooned: 900, loved: 400 }),
    commentCount: 73,
    saveCount: 260,
    shareCount: 120,
  }),
];

// ---------- comments ----------
const C = (c: Omit<Comment, 'reactions' | 'spoiler'> & Partial<Comment>): Comment => ({ reactions: emptyReactions(), spoiler: 'none', ...c });
export const COMMENTS: Comment[] = [
  C({ id: 'c1', postId: 'p-alo-ep3-disc', authorId: 'yuna', body: 'Paused it. You are right about the stamp. I am unwell.', createdAt: ago(18), reactions: rx({ loved: 32, laughed: 8 }) }),
  C({ id: 'c2', postId: 'p-alo-ep3-disc', authorId: 'jae', parentId: 'c1', replyToUserId: 'yuna', body: 'It could also be a letter she wrote to him. The handwriting in the flashback is different.', createdAt: ago(15), reactions: rx({ loved: 12 }) }),
  C({ id: 'c3', postId: 'p-alo-ep3-disc', authorId: 'tobi', body: 'I love this fandom. Someone already screenshotted the envelope at 4x zoom.', createdAt: ago(12), reactions: rx({ laughed: 20 }) }),
  C({ id: 'c4', postId: 'p-alo-ep3-disc', authorId: ME_ID, parentId: 'c1', replyToUserId: 'yuna', body: 'Same. And the music cue under the drawer is the ep 1 pier theme, slowed down.', createdAt: ago(9), reactions: rx({ loved: 6 }) }),
  C({ id: 'c5', postId: 'p-goblin-ending', authorId: 'haru', body: 'A kindness. He finally gets to be the one who is waited for.', createdAt: ago(2 * D), reactions: rx({ loved: 88, cried: 20 }) }),
  C({ id: 'c6', postId: 'p-goblin-ending', authorId: 'lena', body: 'It is a curse and the show knows it — that is why the last line is about the weather, not about love.', createdAt: ago(2 * D - 30), reactions: rx({ loved: 40 }), spoiler: 'ending' }),
  C({ id: 'c7', postId: 'p-goblin-ending', authorId: ME_ID, parentId: 'c5', replyToUserId: 'haru', body: 'This is the reading I want to believe.', createdAt: ago(2 * D - 60), reactions: rx({ loved: 5 }) }),
  C({ id: 'c8', postId: 'p-goblin-rewatch', authorId: 'yuna', body: 'Night one is the best night. Save ep 13 for a weekend.', createdAt: ago(1 * D), reactions: rx({ loved: 14 }) }),
  C({ id: 'c9', postId: 'p-goblin-rewatch', authorId: 'tobi', body: 'The buckwheat field is in my top 3 K-drama frames ever.', createdAt: ago(1 * D - 40), reactions: rx({ loved: 9 }) }),
  C({ id: 'c10', postId: 'p-scandal-ending', authorId: 'sora', body: 'Better. The film ends on the man. The series ends on the women.', createdAt: ago(2 * H), reactions: rx({ loved: 66 }), spoiler: 'ending' }),
  C({ id: 'c11', postId: 'p-scandal-ending', authorId: 'jae', parentId: 'c10', replyToUserId: 'sora', body: 'Exactly this. Ep 8 is a Lady Cho episode disguised as a Jo-won episode.', createdAt: ago(100), reactions: rx({ loved: 21 }), spoiler: 'ending' }),
  C({ id: 'c12', postId: 'p-cloy-recs', authorId: 'sora', body: 'Queen of Tears. Same writer. You will thank me and then you will not.', createdAt: ago(4 * D - 60), reactions: rx({ loved: 44, laughed: 10 }) }),
  C({ id: 'c13', postId: 'p-cloy-recs', authorId: 'haru', body: 'Twenty-Five Twenty-One if you want to be destroyed in a different key.', createdAt: ago(4 * D - 90), reactions: rx({ loved: 31 }) }),
  C({ id: 'c14', postId: 'p-cloy-recs', authorId: 'tobi', body: 'Hometown Cha-Cha-Cha for the soft landing afterwards.', createdAt: ago(4 * D - 120), reactions: rx({ loved: 27 }) }),
  C({ id: 'c15', postId: 'p-reply-review', authorId: ME_ID, body: 'The neighbourhood line is exactly it. You do not watch Reply 1988, you move in.', createdAt: ago(7 * D - 200), reactions: rx({ loved: 19 }) }),
  C({ id: 'c16', postId: 'p-hp-band', authorId: 'dan', body: 'Aloha. It is Aloha. This is not a debate.', createdAt: ago(20 * D - 100), reactions: rx({ laughed: 30, loved: 12 }) }),
  C({ id: 'c17', postId: 'p-alo-ep3-live', authorId: 'sora', body: 'THE PIER.', createdAt: ago(4), reactions: rx({ cried: 12 }) }),
  C({ id: 'c18', postId: 's-2', authorId: 'dan', body: 'The norigae in ep 4 changes colour with her allegiance. Incredible detail.', createdAt: ago(5 * H), reactions: rx({ loved: 40 }) }),
];

// ---------- collections ----------
export const COLLECTIONS: Collection[] = [
  {
    id: 'col-cry',
    ownerId: ME_ID,
    title: 'Cry-proof weekend',
    description: 'For when you want to feel everything and leave the house never.',
    visibility: 'public',
    items: [
      { dramaId: 'my-mister', note: 'Ep 14. You will know.', addedAt: ago(30 * D) },
      { dramaId: 'reply-1988', addedAt: ago(30 * D) },
      { dramaId: 'twenty-five-twenty-one', note: 'Furious-crying, not sad-crying.', addedAt: ago(29 * D) },
      { dramaId: 'when-life-gives-you-tangerines', addedAt: ago(20 * D) },
      { dramaId: 'goblin', addedAt: ago(10 * D) },
    ],
    followerCount: 318,
    updatedAt: ago(10 * D),
  },
  {
    id: 'col-comfort',
    ownerId: ME_ID,
    title: 'Comfort rewatches',
    description: 'No stakes. Warm lighting. Someone is always cooking.',
    visibility: 'public',
    items: [
      { dramaId: 'hometown-cha-cha-cha', addedAt: ago(40 * D) },
      { dramaId: 'hospital-playlist', addedAt: ago(40 * D) },
      { dramaId: 'business-proposal', addedAt: ago(35 * D) },
    ],
    followerCount: 94,
    updatedAt: ago(35 * D),
  },
  {
    id: 'col-private',
    ownerId: ME_ID,
    title: 'Watch with Amaka',
    visibility: 'private',
    items: [
      { dramaId: 'the-scandal', addedAt: ago(2 * D) },
      { dramaId: 'vincenzo', addedAt: ago(12 * D) },
    ],
    followerCount: 0,
    updatedAt: ago(2 * D),
  },
  {
    id: 'col-enemies',
    ownerId: 'sora',
    title: 'Best enemies-to-lovers',
    description: 'Ranked by how long it takes them to admit it.',
    visibility: 'public',
    items: [
      { dramaId: 'business-proposal', note: 'Fast. Too fast. Perfect.', addedAt: ago(50 * D) },
      { dramaId: 'crash-landing-on-you', addedAt: ago(50 * D) },
      { dramaId: 'queen-of-tears', note: 'Married-to-lovers counts.', addedAt: ago(48 * D) },
      { dramaId: 'the-scandal', addedAt: ago(1 * D) },
    ],
    followerCount: 2_140,
    updatedAt: ago(1 * D),
  },
  {
    id: 'col-thrill',
    ownerId: 'lena',
    title: 'Thrillers that respect your intelligence',
    visibility: 'public',
    items: [
      { dramaId: 'signal', addedAt: ago(60 * D) },
      { dramaId: 'the-glory', addedAt: ago(60 * D) },
      { dramaId: 'moving', addedAt: ago(55 * D) },
      { dramaId: 'made-in-korea', note: 'S2 is even tighter.', addedAt: ago(3 * D) },
      { dramaId: 'squid-game', addedAt: ago(50 * D) },
    ],
    followerCount: 1_012,
    updatedAt: ago(3 * D),
  },
  {
    id: 'col-slice',
    ownerId: 'tobi',
    title: 'Slice-of-life starter pack',
    description: 'Start here if you think K-dramas are all love triangles.',
    visibility: 'public',
    items: [
      { dramaId: 'reply-1988', addedAt: ago(70 * D) },
      { dramaId: 'hospital-playlist', addedAt: ago(70 * D) },
      { dramaId: 'my-mister', addedAt: ago(70 * D) },
      { dramaId: 'when-life-gives-you-tangerines', addedAt: ago(20 * D) },
    ],
    followerCount: 877,
    updatedAt: ago(20 * D),
  },
];

// ---------- watchlist (me) ----------
export const WATCHLIST: WatchlistItem[] = [
  { dramaId: 'a-love-other-than-yours', status: 'watching', season: 1, currentEpisode: 2, addedAt: ago(7 * D), updatedAt: ago(6 * D), note: 'Sat nights with Amaka' },
  { dramaId: 'made-in-korea', status: 'watching', season: 2, currentEpisode: 1, addedAt: ago(10 * D), updatedAt: ago(9 * D) },
  { dramaId: 'reply-1988', status: 'watching', season: 1, currentEpisode: 11, addedAt: ago(40 * D), updatedAt: ago(2 * D) },
  { dramaId: 'the-scandal', status: 'want', season: 1, currentEpisode: 0, addedAt: ago(1 * D), updatedAt: ago(1 * D) },
  { dramaId: 'moving', status: 'want', season: 1, currentEpisode: 0, addedAt: ago(15 * D), updatedAt: ago(15 * D) },
  { dramaId: 'signal', status: 'want', season: 1, currentEpisode: 0, addedAt: ago(20 * D), updatedAt: ago(20 * D), note: 'Jae will not shut up about it' },
  { dramaId: 'goblin', status: 'completed', season: 1, currentEpisode: 16, addedAt: ago(200 * D), updatedAt: ago(1 * D), completedAt: ago(180 * D) },
  { dramaId: 'crash-landing-on-you', status: 'completed', season: 1, currentEpisode: 16, addedAt: ago(190 * D), updatedAt: ago(150 * D), completedAt: ago(150 * D) },
  { dramaId: 'the-glory', status: 'completed', season: 1, currentEpisode: 16, addedAt: ago(120 * D), updatedAt: ago(100 * D), completedAt: ago(100 * D) },
  { dramaId: 'business-proposal', status: 'completed', season: 1, currentEpisode: 12, addedAt: ago(90 * D), updatedAt: ago(80 * D), completedAt: ago(80 * D) },
  { dramaId: 'when-life-gives-you-tangerines', status: 'completed', season: 1, currentEpisode: 16, addedAt: ago(60 * D), updatedAt: ago(20 * D), completedAt: ago(20 * D) },
  { dramaId: 'my-mister', status: 'completed', season: 1, currentEpisode: 16, addedAt: ago(300 * D), updatedAt: ago(250 * D), completedAt: ago(250 * D) },
  { dramaId: 'vincenzo', status: 'dropped', season: 1, currentEpisode: 6, addedAt: ago(80 * D), updatedAt: ago(70 * D), note: 'Too loud for me right now' },
];

// ---------- notifications ----------
export const NOTIFICATIONS: Notification[] = [
  { id: 'n1', group: 'drama', kind: 'episode_live', dramaId: 'a-love-other-than-yours', episode: 3, createdAt: ago(10), read: false },
  { id: 'n2', group: 'social', kind: 'reaction', actorIds: ['yuna', 'tobi', 'haru'], postId: 'p-goblin-rewatch', createdAt: ago(35), read: false },
  { id: 'n3', group: 'mentions', kind: 'reply', actorIds: ['jae'], postId: 'p-alo-ep3-disc', commentId: 'c2', createdAt: ago(50), read: false },
  { id: 'n4', group: 'social', kind: 'comment', actorIds: ['yuna'], postId: 'p-goblin-rewatch', commentId: 'c8', createdAt: ago(2 * H), read: false },
  { id: 'n5', group: 'social', kind: 'follow', actorIds: ['dan'], createdAt: ago(5 * H), read: true },
  { id: 'n6', group: 'drama', kind: 'drama_trending', dramaId: 'the-scandal', createdAt: ago(8 * H), read: true },
  { id: 'n7', group: 'mentions', kind: 'mention', actorIds: ['tobi'], postId: 'p-reply-review', createdAt: ago(1 * D), read: true },
  { id: 'n8', group: 'social', kind: 'collection_saved', actorIds: ['lena', 'sora'], collectionId: 'col-cry', createdAt: ago(1 * D + 3 * H), read: true },
  { id: 'n9', group: 'drama', kind: 'episode_aired', dramaId: 'made-in-korea', episode: 2, createdAt: ago(2 * D + 5 * H), read: true },
  { id: 'n10', group: 'system', kind: 'system', title: 'Welcome to Hallyu', body: 'Your dramas. Your people. Your world. Start by following three dramas you are watching.', createdAt: ago(220 * D), read: true },
  { id: 'n11', group: 'social', kind: 'reaction', actorIds: ['sora'], postId: 'p-tangerines-review', createdAt: ago(3 * D), read: true },
  { id: 'n12', group: 'drama', kind: 'episode_aired', dramaId: 'the-ordinary-jackpot', episode: 2, createdAt: ago(2 * D + 7 * H), read: true },
  { id: 'n13', group: 'system', kind: 'system', title: 'Spoiler protection is on', body: 'Posts about episodes you have not watched are veiled. Change this any time in Settings › Content & spoilers.', createdAt: ago(219 * D), read: true },
];

export const FOLLOWED_USERS = ['jae', 'sora', 'tobi', 'yuna', 'haru'];
export const FOLLOWED_DRAMAS = ['a-love-other-than-yours', 'made-in-korea', 'goblin', 'reply-1988', 'the-scandal', 'the-glory'];
export const FOLLOWED_ACTORS = ['gong-yoo', 'iu', 'park-bo-gum', 'kim-tae-ri'];
export const FOLLOWED_COLLECTIONS = ['col-enemies', 'col-slice'];
export const SAVED_POSTS = ['p-scandal-review', 'p-mymister-rec', 'p-reply-review', 's-2'];
export const MY_REACTIONS: Record<string, import('./model').ReactionKind> = { 'p-alo-ep3-disc': 'loved', 'p-reply-review': 'cried', 's-5': 'swooned' };

export const TRENDING_HASHTAGS = ['ALoveOtherThanYours', 'TheScandal', 'MadeInKorea', 'rewatch', 'comfortwatch', 'KimEunSook'];
